name: C++ compiler checker

on: push

jobs:
  runs-on: ubuntu-latest
  - uses: actions/checkout@v4

    makefile_cpp_ex00:
    #runs-on: ubuntu-latest
    steps:
      - name: Compiling c++ files
        run: |
          cd cpp00
          cd ex00
          make workflow

    makefile_cpp_ex01:
    steps:
      - name: Compiling c++ files
        run: |
          cd ../ex01
          make workflow
