name: C++ compiler checker

on: push

jobs:
  makefile_cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compiling c++ files
        run: |
          cd cpp00
          cd ex00
          make workflow
        run: |
          cd ../ex01
          make workflow
